services:
  - type: web
    name: lol-backend-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://launchonlos.fun
      - key: RPC_URL
        value: https://rpc.analos.io/
      - key: EXPLORER_URL
        value: https://explorer.analos.io/