[features]
seeds = false
skip-lint = false

[programs.localnet]
analos_nft_launcher = "NFTLauncher1111111111111111111111111111111"

[programs.devnet]
analos_nft_launcher = "NFTLauncher1111111111111111111111111111111"

[programs.mainnet]
analos_nft_launcher = "NFTLauncher1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.analos.io/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
